services:
  updater:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./index-template.html:/html/index-template.html
      - output:/output
    restart: unless-stopped
  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    # image: nginxinc/nginx-unprivileged:1.28
    ports:
      - "8080:80"
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - output:/usr/share/nginx/html:ro
    restart: unless-stopped
volumes:
  output:
